/**
 * DIS
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Dis) {
      root.Dis = {};
    }
    root.Dis.GetCheckpointResult = factory(root.Dis.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetCheckpointResult model module.
   * @module model/GetCheckpointResult
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>GetCheckpointResult</code>.
   * @alias module:model/GetCheckpointResult
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>GetCheckpointResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCheckpointResult} obj Optional instance to populate.
   * @return {module:model/GetCheckpointResult} The populated <code>GetCheckpointResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('sequence_number')) {
        obj['sequence_number'] = ApiClient.convertToType(data['sequence_number'], 'String');
      }
      if (data.hasOwnProperty('metadata')) {
        obj['metadata'] = ApiClient.convertToType(data['metadata'], 'String');
      }
    }
    return obj;
  }

  /**
   * Unique sequence number of the record for which a checkpoint will be added.
   * @member {String} sequence_number
   */
  exports.prototype['sequence_number'] = undefined;
  /**
   * Metadata of the consumer application.
   * @member {String} metadata
   */
  exports.prototype['metadata'] = undefined;



  return exports;
}));


