/**
 * DIS
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Record'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Record'));
  } else {
    // Browser globals (root is window)
    if (!root.Dis) {
      root.Dis = {};
    }
    root.Dis.GetRecordsResult = factory(root.Dis.ApiClient, root.Dis.Record);
  }
}(this, function(ApiClient, Record) {
  'use strict';




  /**
   * The GetRecordsResult model module.
   * @module model/GetRecordsResult
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>GetRecordsResult</code>.
   * @alias module:model/GetRecordsResult
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>GetRecordsResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetRecordsResult} obj Optional instance to populate.
   * @return {module:model/GetRecordsResult} The populated <code>GetRecordsResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('records')) {
        obj['records'] = ApiClient.convertToType(data['records'], [Record]);
      }
      if (data.hasOwnProperty('next_partition_cursor')) {
        obj['next_partition_cursor'] = ApiClient.convertToType(data['next_partition_cursor'], 'String');
      }
      if (data.hasOwnProperty('millis_behind_latest')) {
        obj['millis_behind_latest'] = ApiClient.convertToType(data['millis_behind_latest'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Record>} records
   */
  exports.prototype['records'] = undefined;
  /**
   * Next cursor, which specifies the next position in the partition from which to start reading data records sequentially.
   * @member {String} next_partition_cursor
   */
  exports.prototype['next_partition_cursor'] = undefined;
  /**
   * @member {Number} millis_behind_latest
   */
  exports.prototype['millis_behind_latest'] = undefined;



  return exports;
}));


