/**
 * DIS
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Dis) {
      root.Dis = {};
    }
    root.Dis.ListStreamsResult = factory(root.Dis.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ListStreamsResult model module.
   * @module model/ListStreamsResult
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>ListStreamsResult</code>.
   * @alias module:model/ListStreamsResult
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>ListStreamsResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListStreamsResult} obj Optional instance to populate.
   * @return {module:model/ListStreamsResult} The populated <code>ListStreamsResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('total_number')) {
        obj['total_number'] = ApiClient.convertToType(data['total_number'], 'Number');
      }
      if (data.hasOwnProperty('stream_names')) {
        obj['stream_names'] = ApiClient.convertToType(data['stream_names'], ['String']);
      }
      if (data.hasOwnProperty('has_more_streams')) {
        obj['has_more_streams'] = ApiClient.convertToType(data['has_more_streams'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Total number of all DIS streams created by the current user.
   * @member {Number} total_number
   */
  exports.prototype['total_number'] = undefined;
  /**
   * Names of N matching DIS streams, where N is equal to or less than the maximum allowed number of DIS streams in the returned stream list.
   * @member {Array.<String>} stream_names
   */
  exports.prototype['stream_names'] = undefined;
  /**
   * An indicator of whether there are more matching DIS streams to list.
   * @member {Boolean} has_more_streams
   * @default false
   */
  exports.prototype['has_more_streams'] = false;



  return exports;
}));


