/**
 * DIS
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OBSDestinationDescriptorRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OBSDestinationDescriptorRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.Dis) {
      root.Dis = {};
    }
    root.Dis.MRSDestinationDescriptorRequest = factory(root.Dis.ApiClient, root.Dis.OBSDestinationDescriptorRequest);
  }
}(this, function(ApiClient, OBSDestinationDescriptorRequest) {
  'use strict';




  /**
   * The MRSDestinationDescriptorRequest model module.
   * @module model/MRSDestinationDescriptorRequest
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>MRSDestinationDescriptorRequest</code>.
   * @alias module:model/MRSDestinationDescriptorRequest
   * @class
   * @implements module:model/OBSDestinationDescriptorRequest
   */
  var exports = function() {
    var _this = this;

    OBSDestinationDescriptorRequest.call(_this);




  };

  /**
   * Constructs a <code>MRSDestinationDescriptorRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MRSDestinationDescriptorRequest} obj Optional instance to populate.
   * @return {module:model/MRSDestinationDescriptorRequest} The populated <code>MRSDestinationDescriptorRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      OBSDestinationDescriptorRequest.constructFromObject(data, obj);
      if (data.hasOwnProperty('mrs_cluster_name')) {
        obj['mrs_cluster_name'] = ApiClient.convertToType(data['mrs_cluster_name'], 'String');
      }
      if (data.hasOwnProperty('mrs_cluster_id')) {
        obj['mrs_cluster_id'] = ApiClient.convertToType(data['mrs_cluster_id'], 'String');
      }
      if (data.hasOwnProperty('mrs_hdfs_path')) {
        obj['mrs_hdfs_path'] = ApiClient.convertToType(data['mrs_hdfs_path'], 'String');
      }
      if (data.hasOwnProperty('hdfs_prefix_folder')) {
        obj['hdfs_prefix_folder'] = ApiClient.convertToType(data['hdfs_prefix_folder'], 'String');
      }
    }
    return obj;
  }

  /**
   * Name of the MRS cluster to which data in the DIS stream will be dumped.
   * @member {String} mrs_cluster_name
   */
  exports.prototype['mrs_cluster_name'] = undefined;
  /**
   * ID of the MRS cluster to which data in the DIS stream will be dumped.
   * @member {String} mrs_cluster_id
   */
  exports.prototype['mrs_cluster_id'] = undefined;
  /**
   * Hadoop Distributed File System (HDFS) path of the MRS cluster to which data in the DIS stream will be dumped.
   * @member {String} mrs_hdfs_path
   */
  exports.prototype['mrs_hdfs_path'] = undefined;
  /**
   * Directory to hold files that will be dumped to the chosen MRS cluster. Different directory levels are separated by a forward slash (/).
   * @member {String} hdfs_prefix_folder
   */
  exports.prototype['hdfs_prefix_folder'] = undefined;

  // Implement OBSDestinationDescriptorRequest interface:
  /**
   * 
   * @member {String} task_name
   */
exports.prototype['task_name'] = undefined;

  /**
   * Name of the agency created in IAM. DIS uses an agency to access your specified resources.
   * @member {String} agency_name
   */
exports.prototype['agency_name'] = undefined;

  /**
   * Directory to hold files that will be dumped to OBS. Different directory levels are separated by a forward slash (/) and cannot start with a forward slash (/).
   * @member {String} file_prefix
   */
exports.prototype['file_prefix'] = undefined;

  /**
   * Directory structure of the Object file written into OBS.
   * @member {String} partition_format
   */
exports.prototype['partition_format'] = undefined;

  /**
   * Name of the OBS bucket used to store data from the DIS stream.
   * @member {String} obs_bucket_path
   */
exports.prototype['obs_bucket_path'] = undefined;

  /**
   * User-defined interval at which data from the DIS stream is imported into OBS.
   * @member {Number} deliver_time_interval
   */
exports.prototype['deliver_time_interval'] = undefined;

  /**
   * This parameter is mandatory if Dump Type is set to Custom file.
   * @member {String} deliver_data_type
   */
exports.prototype['deliver_data_type'] = undefined;



  return exports;
}));


