/**
 * DIS
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Dis) {
      root.Dis = {};
    }
    root.Dis.PartitionResult = factory(root.Dis.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PartitionResult model module.
   * @module model/PartitionResult
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>PartitionResult</code>.
   * @alias module:model/PartitionResult
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>PartitionResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PartitionResult} obj Optional instance to populate.
   * @return {module:model/PartitionResult} The populated <code>PartitionResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('partition_id')) {
        obj['partition_id'] = ApiClient.convertToType(data['partition_id'], 'String');
      }
      if (data.hasOwnProperty('hash_range')) {
        obj['hash_range'] = ApiClient.convertToType(data['hash_range'], 'String');
      }
      if (data.hasOwnProperty('parent_partitions')) {
        obj['parent_partitions'] = ApiClient.convertToType(data['parent_partitions'], 'String');
      }
      if (data.hasOwnProperty('sequence_number_range')) {
        obj['sequence_number_range'] = ApiClient.convertToType(data['sequence_number_range'], 'String');
      }
    }
    return obj;
  }

  /**
   * Current status of each partition.
   * @member {module:model/PartitionResult.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * Unique ID of each partition.
   * @member {String} partition_id
   */
  exports.prototype['partition_id'] = undefined;
  /**
   * Possible value range of the hash key used by each partition.
   * @member {String} hash_range
   */
  exports.prototype['hash_range'] = undefined;
  /**
   * Parent partition.
   * @member {String} parent_partitions
   */
  exports.prototype['parent_partitions'] = undefined;
  /**
   * Sequence number range of each partition.
   * @member {String} sequence_number_range
   */
  exports.prototype['sequence_number_range'] = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "CREATING"
     * @const
     */
    "CREATING": "CREATING",
    /**
     * value: "ACTIVE"
     * @const
     */
    "ACTIVE": "ACTIVE",
    /**
     * value: "DELETED"
     * @const
     */
    "DELETED": "DELETED",
    /**
     * value: "EXPIRED"
     * @const
     */
    "EXPIRED": "EXPIRED"  };


  return exports;
}));


