/**
 * DIS
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Dis) {
      root.Dis = {};
    }
    root.Dis.PutRecordsResultEntry = factory(root.Dis.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PutRecordsResultEntry model module.
   * @module model/PutRecordsResultEntry
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>PutRecordsResultEntry</code>.
   * @alias module:model/PutRecordsResultEntry
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>PutRecordsResultEntry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutRecordsResultEntry} obj Optional instance to populate.
   * @return {module:model/PutRecordsResultEntry} The populated <code>PutRecordsResultEntry</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('partition_id')) {
        obj['partition_id'] = ApiClient.convertToType(data['partition_id'], 'String');
      }
      if (data.hasOwnProperty('sequence_number')) {
        obj['sequence_number'] = ApiClient.convertToType(data['sequence_number'], 'String');
      }
      if (data.hasOwnProperty('error_code')) {
        obj['error_code'] = ApiClient.convertToType(data['error_code'], 'String');
      }
      if (data.hasOwnProperty('error_message')) {
        obj['error_message'] = ApiClient.convertToType(data['error_message'], 'String');
      }
    }
    return obj;
  }

  /**
   * Partition ID for an individual record result.
   * @member {String} partition_id
   */
  exports.prototype['partition_id'] = undefined;
  /**
   * Sequence number of an individual data record.
   * @member {String} sequence_number
   */
  exports.prototype['sequence_number'] = undefined;
  /**
   * Error code for an individual record result.
   * @member {String} error_code
   */
  exports.prototype['error_code'] = undefined;
  /**
   * Error message for an individual record result.
   * @member {String} error_message
   */
  exports.prototype['error_message'] = undefined;



  return exports;
}));


