/**
 * DIS
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Dis) {
      root.Dis = {};
    }
    root.Dis.SchemaField = factory(root.Dis.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SchemaField model module.
   * @module model/SchemaField
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>SchemaField</code>.
   * @alias module:model/SchemaField
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>SchemaField</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SchemaField} obj Optional instance to populate.
   * @return {module:model/SchemaField} The populated <code>SchemaField</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('column_family_name')) {
        obj['column_family_name'] = ApiClient.convertToType(data['column_family_name'], 'String');
      }
      if (data.hasOwnProperty('column_name')) {
        obj['column_name'] = ApiClient.convertToType(data['column_name'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
    }
    return obj;
  }

  /**
   * Name of the HBase column family to which data will be dumped.
   * @member {String} column_family_name
   */
  exports.prototype['column_family_name'] = undefined;
  /**
   * Name of the HBase column to which data will be dumped.
   * @member {String} column_name
   */
  exports.prototype['column_name'] = undefined;
  /**
   * 
   * @member {String} name
   */
  exports.prototype['name'] = undefined;



  return exports;
}));


